# General

default_logdir = '/var/log'
configured_vos = ['cdf', 'cdms', 'darkside', 'dune', 'gm2', 'mars', 'minerva', 'minos', 'mu2e', 'nova', 'sbnd', 'seaquest', 'uboone']

[elasticsearch]
    hostname = 'https://gracc.opensciencegrid.org/q'

# Email
# Set the global email related values under this section

[email]
    # This is the FQDN of the mail server, which GRACC will use to send the email
    smtphost = 'smtp.example.com'

    [email.from]
        name = 'GRACC Operations'  # This is the real name from which the report appears to be emailed from
        email = 'nobody@example.com'  # This is the email from which the reports appears to be emailed from

    # Tester emails
    [email.test]
        names = ['Test Recipient', ]
        emails = ['nobody@example.com', ]

# VO substitutions
# For VOs such as uboone, where we might expect to see uboone in raw records
# and microboone in the summary records due to name correction, make sure we
# have a list for each VO of the "valid_vos".

[uboone]
    valid_vos = ['uboone', 'microboone']

# Report-specific parameters
# Note that in TOML, True and False must be all lowercase.  Seems weird, but there you go.

[efficiency]
    index_pattern='gracc.osg.raw-%Y.%m'

	[efficiency.cdf]
	min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.cdms]
        min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.darkside]
	min_hours = 500
        min_efficiency = 0.35
        to_emails = ['nobody@example.com', ]

	[efficiency.dune]
        min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.gm2]
        min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.mars]
        min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.minerva]
        min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.minos]
        min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.mu2e]
        min_hours = 1000
        min_efficiency = 0.5
        commonname = '/CN=production/mu2egpvm01.fnal.gov'
        to_emails = ['nobody@example.com', ]

	[efficiency.nova]
        min_hours=1000
        min_efficiency=0.5
        commonname='/CN=novaproduction/nova-offline.fnal.gov'
        to_emails = ['nobody@example.com', ]

	[efficiency.sbnd]
        min_hours = 500
        min_efficiency = 0.65
        to_emails = ['nobody@example.com', ]

	[efficiency.seaquest]
        min_hours = 1000
        min_efficiency = 0.5
        to_emails = ['nobody@example.com', ]

	[efficiency.uboone]
        min_hours = 1000
        min_efficiency = 0.5
        commonname ='/CN=uboonepro/uboonegpvm01.fnal.gov'
        to_emails = ['nobody@example.com', ]


[jobsuccessrate]
    index_pattern='gracc.osg.raw-%Y.%m'

	[jobsuccessrate.darkside]
        fqan = '/fermilab/darkside/Role=*'
        to_emails = ['nobody@example.com', ]
        no_production = true

	[jobsuccessrate.dune]
        fqan = '/dune/Role=Production/Capability=NULL'
        to_emails = ['nobody@example.com', ]

	[jobsuccessrate.mu2e]
        fqan = '/fermilab/mu2e/Role=Production/Capability=NULL'
        to_emails = ['nobody@example.com', ]

	[jobsuccessrate.nova]
        # num_clusters = 100
        jobs_per_cluster = 20
        # num_failed_sites = 20
        # num_hosts_per_site = 20
        # errors_per_host = 20
        fqan = '/fermilab/nova/Role=Production/Capability=NULL'
        to_emails = ['nobody@example.com', ]

	[jobsuccessrate.seaquest]
        fqan = '/fermilab/seaquest/Role=*'
        to_emails = ['nobody@example.com', ]
        no_production = true

	[jobsuccessrate.uboone]
        fqan = '/fermilab/uboone/Role=Production/Capability=NULL'
        to_emails = ['nobody@example.com', ]


[topwastedhoursvo]
    index_pattern='gracc.osg.summary'

	[topwastedhoursvo.darkside]
        perc_cutoff = 0
        hours_cutoff = 0
        #numrank = 100
        to_emails = ['nobody@example.com', ]

	[topwastedhoursvo.dune]
        perc_cutoff = 0
        hours_cutoff = 0
        to_emails = ['nobody@example.com', ]

	[topwastedhoursvo.mu2e]
        perc_cutoff = 0
        hours_cutoff = 0
        to_emails = ['nobody@example.com', ]

	[topwastedhoursvo.nova]
        perc_cutoff = 0
        hours_cutoff = 0
        #numrank = 10
        to_emails = ['nobody@example.com', ]

	[topwastedhoursvo.seaquest]
        perc_cutoff = 0
        hours_cutoff = 0
        to_emails = ['nobody@example.com', ]

	[topwastedhoursvo.uboone]
        perc_cutoff = 0
        hours_cutoff = 0
        to_emails = ['nobody@example.com', ]


