# General

default_logdir = '/var/log'

[elasticsearch]
    hostname = 'https://gracc.opensciencegrid.org/q'

# Email
# Set the global email related values under this section
[email]
    # This is the FQDN of the mail server, which GRACC will use to send the email
    smtphost = 'smtp.example.com'

    [email.from]
        name = 'GRACC Operations'  # This is the real name from which the report appears to be emailed from
        email = 'nobody@example.com'  # This is the email from which the reports appears to be emailed from

    # Tester emails
    [email.test]
        names = ['Test Recipient', ]
        emails = ['nobody@example.com', ]

# Report-specific parameters
[flocking]
    probe_list = ['condor:amundsen.grid.uchicago.edu',
        'condor:csiu.grid.iu.edu', 'condor:glide.bakerlab.org',
        'condor:gw68.quarry.iu.teragrid.org', 'condor:iplant-condor-iu.tacc.utexas.edu',
        'condor:iplant-condor.tacc.utexas.edu', 'condor:otsgrid.iit.edu',
        'condor:scott.grid.uchicago.edu', 'condor:submit1.bioinformatics.vt.edu',
        'condor:submit.mit.edu', 'condor:SUBMIT.MIT.EDU', 'condor:workflow.isi.edu']
    to_emails = ['nobody@example.com', ]
    to_names = ['Recipient Name', ]


[news]
    OSG_flocking_probe_list = ['condor:osg-xsede.grid.iu.edu', 'condor:gw68.quarry.iu.teragrid.org',
        'condor:xd-login.opensciencegrid.org', 'condor:csiu.grid.iu.edu',
        'condor:submit1.bioinformatics.vt.edu', 'condor:iplant-condor.tacc.utexas.edu',
        'condor:workflow.isi.edu', 'condor:osg-xsede.grid.iu.edu',
        'condor:xd-login.opensciencegrid.org', 'condor:ce04.cmsaf.mit.edu',
        'condor:csiu.grid.iu.edu', 'condor:submit.mit.edu', 'condor:login01.osgconnect.net',
        'condor:login.ci-connect.uchicago.edu', 'condor:login.umich.ci-connect.net',
        'condor:login02.osgconnect.net', 'condor:login03.osgconnect.net',
        'condor:login.usatlas.org', 'condor:login.duke.ci-connect.net',
        'condor:login.xenon.ci-connect.net', 'condor:login.duke.ci-connect.net']
    to_emails = ['nobody@example.com', ]
    to_names = ['Recipient Name', ]

[probe]
    to_emails = ['nobody@example.com', ]
    to_names = ['Recipient Name', ]

[project]
    [project.xd]
        probe_list = ['condor:osg-xsede.grid.iu.edu', 'condor:gw68.quarry.iu.teragrid.org', 'condor:xd-login.opensciencegrid.org']
        admins_to_emails = ['nobody@example.com', ]
        admins_to_names = ['Recipient Name',]
        to_emails = ['nobody@example.com', ]
        to_names = ['Recipient Name',]

    [project.osg]
        probe_list = ['condor:submit1.bioinformatics.vt.edu', 'condor:iplant-condor.tacc.utexas.edu', 'condor:workflow.isi.edu', 'condor:osg-xsede.grid.iu.edu', 'condor:xd-login.opensciencegrid.org', 'condor:ce04.cmsaf.mit.edu']
        to_emails = ['nobody@example.com', ]
        to_names = ['Recipient Name',]

    [project.osg-connect]
        probe_list = ['condor:login01.osgconnect.net', 'condor:login.ci-connect.uchicago.edu', 'condor:login.umich.ci-connect.net', 'condor:login02.osgconnect.net', 'condor:login03.osgconnect.net', 'condor:login.usatlas.org', 'condor:login.xenon.ci-connect.net']
        to_emails = ['nobody@example.com', ]
        to_names = ['Recipient Name',]

[siteusage]
    to_emails = ['nobody@example.com', ]
    to_names = ['Recipient Name', ]

[wastedhours]
    to_emails = ['nobody@example.com', ]
    to_names = ['Recipient Name', ]

[namecorrection]
    mwt2url = 'http://myosg.grid.iu.edu/rgsummary/xml?summary_attrs_showfqdn=on&current_status_attrs_shownc=on&gip_status_attrs_showtestresults=on&downtime_attrs_showpast=&account_type=cumulative_hours&ce_account_type=gip_vo&se_account_type=vo_transfer_volume&bdiitree_type=total_jobs&bdii_object=service&bdii_server=is-osg&facility_sel[]=10023&rg=on&rg_sel[]=310&gridtype=on&gridtype_1=on&service=on&service_sel[]=1&active=on&active_value=1&disable_value=1'

# Databases
# XD database
[xd_db]
    hostname = 'tgcdb.xsede.org'
    port = 5432
    username = 'USERNAME'
    password = 'PASSWORD'
    schema = 'teragrid'

